export const templateTexts = {
  "Fundament EXC3 ": {
    B5: {
      "Header 5": {
        1: "100%",
        2: "20% / Maks.",
        3: "20% / Maks.",
        4: "20% / Maks.",
        5: "20% / Maks.",
        6: "20% / Maks.",
      },
      "Header 1": {
        1: "1",
        2: "2",
        3: "3",
        4: "4",
        5: "5",
        6: "6",
      },
      "Header 4": {
        1: "Uafhængig kontrollant udfører kontrol af egenkontrol, suppleret med kontrol af udvalgte dele - som vurderes størst risiko for fejl",
        2: "Udgravningsdimensioner stemmer overens med konstruktionstegninger +-15 mm",
        3: "Udgravningen er fri for fremmede legemer og nedskridning",
        4: "Armeringsmængde og afstande stemmer overens med konstruktionstegninger +-10mm",
        5: "Dæklag som foreskrevet på konstruktionstegninger +-10mm",
        6: "Fundamente stemmer overens med konstruktionstegninger og overholder følgende udførelsestolerancer:\nKote: +5/-15 mm\nPosition i planet: +-25mm\nPlanhed: 9mm/2m",
      },
      "Header 3": {
        1: "Under udførelse",
        2: "Før støbning",
        3: "Før støbning",
        4: "Efter montering, før støbning",
        5: "Efter montering, før støbning",
        6: "Før og efter støbning",
      },
      "Header 6": {
        1: "Visuel kontrol",
        2: "Visuelt + Måling",
        3: "Visuelt + Fotodokumentation",
        4: "Visuel + Måling",
        5: "Visuel + Måling",
        6: "Visuel + Måling",
      },
      "Header 2": {
        1: "Kontrol af egenkontrol er udført",
        2: "Udgravningsdimensioner",
        3: "Fri udgravning",
        4: "Armering",
        5: "Dæklag",
        6: "Kote, placering og planhed",
      },
      "Header 7": {
        1: "Uafhængig kontrollant har gennemgået egenkontrollen og hvilke udvalgte dele som er udført supplerende kontrol på. Der redegøres for valget af udvalgte dele",
        2: "Angiv den afmålte geometri i kontrolresultatet, evt. med supplerende fotodokumentation. ",
        3: "Angiv afvigelser og bemærkninger i kontrolresultatet, suppleres med fotodokumentation",
        4: "Angiv de anvendte armeringsstørrelser, armerings afstande i kontrolresultat, evt. med supplerende fotodokumentation af opmåling. ",
        5: "Angiv det afmålte dæklag, evt. med supplerende fotodokumentation af opmåling. ",
        6: "Angiv det afmålte",
      },
    },
    B6: {
      "Header 6": {
        1: "Visuel kontrol",
        2: "Visuel kontrol",
        3: "Visuel kontrol",
      },
      "Header 2": {
        1: "Kontrol af egenkontrol er udført",
        2: "Overordnede geometriske mål, placering og udførelse er korrekt",
        3: "Konstruktionens overordnede funktion og tilstand",
      },
      "Header 3": {
        1: "Efter udførelse",
        2: "Efter udførelse",
        3: "Efter udførelse",
      },
      "Header 4": {
        1: "Uafhængig kontrollant udfører kontrol af egenkontrol, suppleret med kontrol af udvalgte dele - som vurderes størst risiko for fejl",
        2: "Ingen afvigelser som overgår udførelsestolerancerne",
        3: "Ingen store deformationer, revner eller tegn på overbelastning",
      },
      "Header 5": {
        1: "100%",
        2: "100%",
        3: "100%",
      },
      "Header 1": {
        1: "1",
        2: "2",
        3: "3",
      },
      "Header 7": {
        1: "Uafhængig kontrollant har gennemgået egenkontrollen og hvilke udvalgte dele som er udført supplerende kontrol på. Der redegøres for valget af udvalgte dele",
        2: "Angiv kontrolleret punkter med eventuelle afvigelser i kontrolresultat. Understøttes af fotodokumentation.",
        3: "Angiv afvigelser i kontrolresultat. Der skal foreligge fotodokumentation om der forekommer afvigelser eller ej. ",
      },
    },
    B4: {
      "Header 5": {
        1: "100%",
        2: "20%",
        3: "20%",
        4: "20%",
      },
      "Header 7": {
        1: "Uafhængig kontrollant har gennemgået egenkontrollen og hvilke udvalgte dele som er udført supplerende kontrol på. Der redegøres for valget af udvalgte dele",
        2: "Angiv betonklasse, mængde og leverandør på følgesedlen i kontrolresultatet",
        3: "Angiv armeringstype, -størrelser, mængder og leverandør på følgesedlen i kontrolresultatet",
        4: "Angivning af evt. fejl eller skader. I tilfælde af ingen fejl og mangler, skal der stadig foreligge billeddokumentation på dette. ",
      },
      "Header 6": {
        1: "Visuel kontrol",
        2: "Følgesedler/Visuel",
        3: "Følgesedler/Visuel",
        4: "Billeddokumentation/Visuelt",
      },
      "Header 3": {
        1: "Ved modtagelse",
        2: "Ved levering",
        3: "Ved levering",
        4: "Ved levering",
      },
      "Header 4": {
        1: "Uafhængig kontrollant udfører kontrol af egenkontrol, suppleret med kontrol af udvalgte dele - som vurderes størst risiko for fejl",
        2: "Følgende fremgår ved modtagelse, og i overensstemmelse med bestilte:\nCE-mærkning, Betonklasse, og mængde",
        3: "Følgende fremgår ved modtagelse, og i overensstemmelse med bestilte:\nCE-mærkning, armeringstype, -størrelser og mængder.",
        4: "Det leveret har ingen synlige fejl og mangler:\nTransportskader eller fejl fra produktion",
      },
      "Header 2": {
        1: "Kontrol af egenkontrol er udført",
        2: "Beton",
        3: "Armering",
        4: "Fejl og mangler",
      },
      "Header 1": {
        1: "1",
        2: "2",
        3: "3",
        4: "4",
      },
    },
    B1: {
      "Header 4": {
        1: "Uafhængig kontrollant udfører kontrol af egenkontrol, suppleret med kontrol af udvalgte dele - som vurderes størst risiko for fejl",
        2: "Følgende fremgår: \nKonsekvensklasse,\nKonstruktionsklasse, Geoteknisk klasse og\nUdførelsesklasse",
        3: "Følgende fremgår:\nBetonklasse, Eksponeringsklassen, Armeringstype",
        5: "Følgende fremgår:\nTværsnit, Dæklag, Armeringstørrelse, Armeringsplacering",
        6: "Følgende koter fremgår:\nKote på fundamenter",
      },
      "Header 5": {
        1: "100%",
        2: "100%",
        3: "100%",
        5: "100%",
        6: "100%",
      },
      "Header 1": {
        1: "1",
        2: "2",
        3: "3",
        5: "4",
        6: "5",
      },
      "Header 7": {
        1: "Uafhængig kontrollant har gennemgået egenkontrollen og hvilke udvalgte dele som er udført supplerende kontrol på",
        2: "Angivning af klasser i kontrolresultat",
        3: "Angivning af materialeklasser i kontrolresultat",
        5: "Angivning af geometri i kontrolresultat",
        6: "Angivning af koter i kontrolresultat",
      },
      "Header 6": {
        1: "Visuel kontrol",
        2: "Visuel kontrol",
        3: "Visuel kontrol",
        5: "Visuel kontrol",
        6: "Visuel kontrol",
      },
      "Header 3": {
        1: "Inden opstart",
        2: "Inden opstart",
        3: "Inden opstart",
        5: "Inden opstart",
        6: "Inden opstart",
      },
      "Header 2": {
        1: "Kontrol af egenkontrol er udført",
        2: "Kontrol af klasser",
        3: "Materialeklasser",
        5: "Geometri",
        6: "Koter",
      },
    },
    B3: {
      "Header 7": {
        1: "Uafhængig kontrollant har gennemgået egenkontrollen og hvilke udvalgte dele som er udført supplerende kontrol på. Der redegøres for valget af udvalgte dele",
        2: "Angivelse af bestilte/indkøbte materialer i kontrolresultatet",
        3: "Angivelse leverandør(er) i kontrolresultat",
      },
      "Header 2": {
        1: "Kontrol af egenkontrol er udført",
        2: "Indkøb/bestilling",
        3: "CE-Mærke",
      },
      "Header 6": {
        1: "Visuel kontrol",
        2: "Visuel kontrol",
        3: "Visuel kontrol",
      },
      "Header 5": {
        1: "100%",
        2: "20%",
        3: "20%",
      },
      "Header 3": {
        1: "Inden opstart",
        2: "Inden opstart",
        3: "Inden opstart",
      },
      "Header 1": {
        1: "1",
        2: "2",
        3: "3",
      },
      "Header 4": {
        1: "Uafhængig kontrollant udfører kontrol af egenkontrol, suppleret med kontrol af udvalgte dele - som vurderes størst risiko for fejl",
        2: "Overensstemmelse med udførelsesgrundlaget af materialeklasser for følgende:\nBeton, Armering ",
        3: "Byggevarer leveres CE-mærket.",
      },
    },
    B2: {
      "Header 3": {
        1: "Inden opstart",
        2: "Inden opstart",
        3: "Inden opstart",
        4: "Inden opstart",
      },
      "Header 6": {
        1: "Visuel kontrol",
        2: "Visuel kontrol",
        3: "Visuel kontrol",
        4: "Visuel kontrol",
      },
      "Header 2": {
        1: "Kontrol af egenkontrol er udført",
        2: "Informationer",
        3: "Bygbarhed",
        4: "Arbejdsmiljø",
      },
      "Header 1": {
        1: "1",
        2: "2",
        3: "3",
        4: "4",
      },
      "Header 7": {
        1: "Uafhængig kontrollant har gennemgået egenkontrollen og hvilke udvalgte dele som er udført supplerende kontrol på. Der redegøres for valget af udvalgte dele",
        2: "Angivelse af dokument/tegnings nr. hvor kontrollen er udført, hertil oplistes acceptkriterier i kontrolresultatet",
        3: "Angivelse af dokument/tegnings nr. hvor kontrollen er udført, hertil oplistes acceptkravene, med vurdering om det er bygbart i kontrolresultatet.",
        4: "Angivelse af dokument/tegnings nr. hvor kontrollen er udført, og en vurdering heraf.",
      },
      "Header 4": {
        1: "Uafhængig kontrollant udfører kontrol af egenkontrol, suppleret med kontrol af udvalgte dele - som vurderes størst risiko for fejl",
        2: "Følgende fremgår tydeligt:\nUdførelsesklasser, materialekrav og tolerancer",
        3: "Der fremgår tilstrækkeligt materiale til følgende:\nudførlighed, tolerancer, materialer, grænseflader ",
        4: "Kan håndteres sikkert og under overholdelse af gældende arbejdsmiljøsregler",
      },
      "Header 5": {
        1: "100%",
        2: "20%",
        3: "20%",
        4: "20%",
      },
    },
  },

  "Fundamenter EXC2": {
    B5: {
      "Header 3": {
        1: "Under udførelse",
        2: "Før støbning",
        3: "Før støbning",
        4: "Efter montering, før støbning",
        5: "Efter montering, før støbning",
        6: "Før og efter støbning",
      },
      "Header 5": {
        1: "100%",
        2: "10%",
        3: "10%",
        4: "10%",
        5: "10%",
        6: "10%",
      },
      "Header 7": {
        1: "Uafhængig kontrollant har gennemgået egenkontrollen og hvilke udvalgte dele som er udført supplerende kontrol på",
        2: "Angiv den afmålte geometri i kontrolresultatet, evt. med supplerende fotodokumentation. ",
        3: "Angiv afvigelser og bemærkninger i kontrolresultatet, suppleres med fotodokumentation",
        4: "Angiv de anvendte armeringsstørrelser, armerings afstande i kontrolresultat, evt. med supplerende fotodokumentation af opmåling. ",
        5: "Angiv det afmålte dæklag, evt. med supplerende fotodokumentation af opmåling. ",
        6: "Angiv det afmålte",
      },
      "Header 4": {
        1: "Uafhængig kontrollant udfører kontrol af egenkontrol, suppleret med kontrol af udvalgte dele - som vurderes størst risiko for fejl",
        2: "Udgravningsdimensioner stemmer overens med konstruktionstegninger +-15 mm",
        3: "Udgravningen er fri for fremmede legemer og nedskridning",
        4: "Armeringsmængde og afstande stemmer overens med konstruktionstegninger +-10mm",
        5: "Dæklag som foreskrevet på konstruktionstegninger +-10mm",
        6: "Fundamente stemmer overens med konstruktionstegninger og overholder følgende udførelsestolerancer:\nKote: +5/-15 mm\nPosition i planet: +-25mm\nPlanhed: 9mm/2m",
      },
      "Header 2": {
        1: "Kontrol af egenkontrol er udført",
        2: "Udgravningsdimensioner",
        3: "Fri udgravning",
        4: "Armering",
        5: "Dæklag",
        6: "Kote, placering og planhed",
      },
      "Header 1": {
        1: "1",
        2: "2",
        3: "3",
        4: "4",
        5: "5",
        6: "6",
      },
      "Header 6": {
        1: "Visuel kontrol",
        2: "Visuelt + Måling",
        3: "Visuelt + Fotodokumentation",
        4: "Visuel + Måling",
        5: "Visuel + Måling",
        6: "Visuel + Måling",
      },
    },
    B3: {
      "Header 5": {
        1: "100%",
        2: "10%",
        3: "10%",
      },
      "Header 7": {
        1: "Uafhængig kontrollant har gennemgået egenkontrollen og hvilke udvalgte dele som er udført supplerende kontrol på",
        2: "Angivelse af bestilte/indkøbte materialer i kontrolresultatet",
        3: "Angivelse leverandør(er) i kontrolresultat",
      },
      "Header 3": {
        1: "Inden opstart",
        2: "Inden opstart",
        3: "Inden opstart",
      },
      "Header 2": {
        1: "Kontrol af egenkontrol er udført",
        2: "Indkøb/bestilling",
        3: "CE-Mærke",
      },
      "Header 6": {
        1: "Visuel kontrol",
        2: "Visuel kontrol",
        3: "Visuel kontrol",
      },
      "Header 1": {
        1: "1",
        2: "2",
        3: "3",
      },
      "Header 4": {
        1: "Uafhængig kontrollant udfører kontrol af egenkontrol, suppleret med kontrol af udvalgte dele - som vurderes størst risiko for fejl",
        2: "Overensstemmelse med udførelsesgrundlaget af materialeklasser for følgende:\nBeton, Armering ",
        3: "Byggevarer leveres CE-mærket.",
      },
    },
    B2: {
      "Header 5": {
        1: "100%",
        2: "10%",
        3: "10%",
        4: "10%",
      },
      "Header 2": {
        1: "Kontrol af egenkontrol er udført",
        2: "Informationer",
        3: "Bygbarhed",
        4: "Arbejdsmiljø",
      },
      "Header 7": {
        1: "Uafhængig kontrollant har gennemgået egenkontrollen og hvilke udvalgte dele som er udført supplerende kontrol på",
        2: "Angivelse af dokument/tegnings nr. hvor kontrollen er udført, hertil oplistes acceptkriterier i kontrolresultatet",
        3: "Angivelse af dokument/tegnings nr. hvor kontrollen er udført, hertil oplistes acceptkravene, med vurdering om det er bygbart i kontrolresultatet.",
        4: "Angivelse af dokument/tegnings nr. hvor kontrollen er udført, og en vurdering heraf.",
      },
      "Header 1": {
        1: "1",
        2: "2",
        3: "3",
        4: "4",
      },
      "Header 4": {
        1: "Uafhængig kontrollant udfører kontrol af egenkontrol, suppleret med kontrol af udvalgte dele - som vurderes størst risiko for fejl",
        2: "Følgende fremgår tydeligt:\nUdførelsesklasser, materialekrav og tolerancer",
        3: "Der fremgår tilstrækkeligt materiale til følgende:\nudførlighed, tolerancer, materialer, grænseflader ",
        4: "Kan håndteres sikkert og under overholdelse af gældende arbejdsmiljøsregler",
      },
      "Header 6": {
        1: "Visuel kontrol",
        2: "Visuel kontrol",
        3: "Visuel kontrol",
        4: "Visuel kontrol",
      },
      "Header 3": {
        1: "Inden opstart",
        2: "Inden opstart",
        3: "Inden opstart",
        4: "Inden opstart",
      },
    },
    B4: {
      "Header 2": {
        1: "Kontrol af egenkontrol er udført",
        2: "Beton",
        3: "Armering",
        4: "Fejl og mangler",
      },
      "Header 6": {
        1: "Visuel kontrol",
        2: "Følgesedler/Visuel",
        3: "Følgesedler/Visuel",
        4: "Billeddokumentation/Visuelt",
      },
      "Header 7": {
        1: "Uafhængig kontrollant har gennemgået egenkontrollen og hvilke udvalgte dele som er udført supplerende kontrol på",
        2: "Angiv betonklasse, mængde og leverandør på følgesedlen i kontrolresultatet",
        3: "Angiv armeringstype, -størrelser, mængder og leverandør på følgesedlen i kontrolresultatet",
        4: "Angivning af evt. fejl eller skader. I tilfælde af ingen fejl og mangler, skal der stadig foreligge billeddokumentation på dette. ",
      },
      "Header 4": {
        1: "Uafhængig kontrollant udfører kontrol af egenkontrol, suppleret med kontrol af udvalgte dele - som vurderes størst risiko for fejl",
        2: "Følgende fremgår ved modtagelse, og i overensstemmelse med bestilte:\nCE-mærkning, Betonklasse, og mængde",
        3: "Følgende fremgår ved modtagelse, og i overensstemmelse med bestilte:\nCE-mærkning, armeringstype, -størrelser og mængder.",
        4: "Det leveret har ingen synlige fejl og mangler:\nTransportskader eller fejl fra produktion",
      },
      "Header 5": {
        1: "100%",
        2: "10%",
        3: "10%",
        4: "10%",
      },
      "Header 1": {
        1: "1",
        2: "2",
        3: "3",
        4: 4,
      },
      "Header 3": {
        1: "Ved modtagelse",
        2: "Ved levering",
        3: "Ved levering",
        4: "Ved levering",
      },
    },
    B1: {
      "Header 3": {
        1: "Inden opstart",
        2: "Inden opstart",
        3: "Inden opstart",
        5: "Inden opstart",
        6: "Inden opstart",
      },
      "Header 5": {
        1: "100%",
        2: "100%",
        3: "100%",
        5: "100%",
        6: "100%",
      },
      "Header 2": {
        1: "Kontrol af egenkontrol er udført",
        2: "Kontrol af klasser",
        3: "Materialeklasser",
        5: "Geometri",
        6: "Koter",
      },
      "Header 7": {
        1: "Uafhængig kontrollant har gennemgået egenkontrollen og hvilke udvalgte dele som er udført supplerende kontrol på",
        2: "Angivning af klasser i kontrolresultat",
        3: "Angivning af materialeklasser i kontrolresultat",
        5: "Angivning af geometri i kontrolresultat",
        6: "Angivning af koter i kontrolresultat",
      },
      "Header 6": {
        1: "Visuel kontrol",
        2: "Visuel kontrol",
        3: "Visuel kontrol",
        5: "Visuel kontrol",
        6: "Visuel kontrol",
      },
      "Header 4": {
        1: "Uafhængig kontrollant udfører kontrol af egenkontrol, suppleret med kontrol af udvalgte dele - som vurderes størst risiko for fejl",
        2: "Følgende fremgår: \nKonsekvensklasse,\nKonstruktionsklasse, Genoteknisk klasse og\nUdførelsesklasse",
        3: "Følgende fremgår:\nBetonklasse, Eksponeringsklassen, Armeringstype",
        5: "Følgende fremgår:\nTværsnit, Dæklag, Armeringstørrelse, Armeringsplacering",
        6: "Følgende koter fremgår:\nKote på fundamenter",
      },
      "Header 1": {
        1: "1",
        2: "2",
        3: "3",
        5: "4",
        6: "5",
      },
    },
    B6: {
      "Header 2": {
        1: "Kontrol af egenkontrol er udført",
        2: "Overordnede geometriske mål, placering og udførelse er korrekt",
        3: "Konstruktionens overordnede funktion og tilstand",
      },
      "Header 4": {
        1: "Uafhængig kontrollant udfører kontrol af egenkontrol, suppleret med kontrol af udvalgte dele - som vurderes størst risiko for fejl",
        2: "Ingen afvigelser som overgår udførelsestolerancerne",
        3: "Ingen store deformationer, revner eller tegn på overbelastning",
      },
      "Header 5": {
        1: "100%",
        2: "100%",
        3: "100%",
      },
      "Header 1": {
        1: "1",
        2: "2",
        3: "3",
      },
      "Header 6": {
        1: "Visuel kontrol",
        2: "Visuel kontrol",
        3: "Visuel kontrol",
      },
      "Header 3": {
        1: "Efter udførelse",
        2: "Efter udførelse",
        3: "Efter udførelse",
      },
      "Header 7": {
        1: "Uafhængig kontrollant har gennemgået egenkontrollen og hvilke udvalgte dele som er udført supplerende kontrol på",
        2: "Angiv kontrolleret punkter med eventuelle afvigelser i kontrolresultat. Understøttes af fotodokumentation.",
        3: "Angiv afvigelser i kontrolresultat. Der skal foreligge fotodokumentation om der forekommer afvigelser eller ej. ",
      },
    },
  },

  "Tom skabelon": {
    B1: {
      "Header 1": {
        1: "1",
        2: "2",
        3: "3",
      },
      "Header 2": {
        1: "",
        2: "",
        3: "",
      },
      "Header 3": {
        1: "",
        2: "",
        3: "",
      },
      "Header 4": {
        1: "",
        2: "",
        3: "",
      },
      "Header 5": {
        1: "",
        2: "",
        3: "",
      },
      "Header 6": {
        1: "",
        2: "",
        3: "",
      },
      "Header 7": {
        1: "",
        2: "",
        3: "",
      },
    },
    B2: {
      "Header 1": {
        1: "1",
        2: "2",
        3: "3",
      },
      "Header 2": {
        1: "",
        2: "",
        3: "",
      },
      "Header 3": {
        1: "",
        2: "",
        3: "",
      },
      "Header 4": {
        1: "",
        2: "",
        3: "",
      },
      "Header 5": {
        1: "",
        2: "",
        3: "",
      },
      "Header 6": {
        1: "",
        2: "",
        3: "",
      },
      "Header 7": {
        1: "",
        2: "",
        3: "",
      },
    },
    B3: {
      "Header 1": {
        1: "1",
        2: "2",
        3: "3",
      },
      "Header 2": {
        1: "",
        2: "",
        3: "",
      },
      "Header 3": {
        1: "",
        2: "",
        3: "",
      },
      "Header 4": {
        1: "",
        2: "",
        3: "",
      },
      "Header 5": {
        1: "",
        2: "",
        3: "",
      },
      "Header 6": {
        1: "",
        2: "",
        3: "",
      },
      "Header 7": {
        1: "",
        2: "",
        3: "",
      },
    },
    B4: {
      "Header 1": {
        1: "1",
        2: "2",
        3: "3",
      },
      "Header 2": {
        1: "",
        2: "",
        3: "",
      },
      "Header 3": {
        1: "",
        2: "",
        3: "",
      },
      "Header 4": {
        1: "",
        2: "",
        3: "",
      },
      "Header 5": {
        1: "",
        2: "",
        3: "",
      },
      "Header 6": {
        1: "",
        2: "",
        3: "",
      },
      "Header 7": {
        1: "",
        2: "",
        3: "",
      },
    },
    B5: {
      "Header 1": {
        1: "1",
        2: "2",
        3: "3",
      },
      "Header 2": {
        1: "",
        2: "",
        3: "",
      },
      "Header 3": {
        1: "",
        2: "",
        3: "",
      },
      "Header 4": {
        1: "",
        2: "",
        3: "",
      },
      "Header 5": {
        1: "",
        2: "",
        3: "",
      },
      "Header 6": {
        1: "",
        2: "",
        3: "",
      },
      "Header 7": {
        1: "",
        2: "",
        3: "",
      },
    },
    B6: {
      "Header 1": {
        1: "1",
        2: "2",
        3: "3",
      },
      "Header 2": {
        1: "",
        2: "",
        3: "",
      },
      "Header 3": {
        1: "",
        2: "",
        3: "",
      },
      "Header 4": {
        1: "",
        2: "",
        3: "",
      },
      "Header 5": {
        1: "",
        2: "",
        3: "",
      },
      "Header 6": {
        1: "",
        2: "",
        3: "",
      },
      "Header 7": {
        1: "",
        2: "",
        3: "",
      },
    },
  },
};
